### ISSUE TITLE
TypeError: 'NoneType' object is not subscriptable

### ISSUE THREAD

**Issue by yiyele** [TsinghuaAI/CPM-1-Finetune#26]
Traceback (most recent call last):
  File "finetune_lm.py", line 315, in <module>
    main()
  File "finetune_lm.py", line 206, in main
    model, optimizer, lr_scheduler = setup_model_and_optimizer(args)
  File "/CPM/model/CDialoGPT/CPM-Finetune/utils.py", line 513, in setup_model_and_optimizer
    args.iteration = load_checkpoint(model, optimizer, lr_scheduler, args)
  File "/CPM/model/CDialoGPT/CPM-Finetune/utils.py", line 281, in load_checkpoint
    checkpoint_name, sd = model.load_checkpoint(args.load, iteration, load_module_strict=False, load_optimizer_states=False, load_lr_scheduler_states=False)
  File "/usr/local/lib/python3.6/dist-packages/deepspeed/runtime/engine.py", line 1196, in load_checkpoint
    load_lr_scheduler_states=load_lr_scheduler_states)
  File "/usr/local/lib/python3.6/dist-packages/deepspeed/runtime/engine.py", line 1231, in _load_checkpoint
    self.optimizer.load_state_dict(checkpoint['optimizer'])
  File "/usr/local/lib/python3.6/dist-packages/torch/optim/optimizer.py", line 108, in load_state_dict
    saved_groups = state_dict['param_groups']
TypeError: 'NoneType' object is not subscriptable

**Comment by t1101675** [comment]
您用的是我们要求的 deepspeed 版本吗？ 可以参考 #21

**Comment by yiyele** [comment]
你们提供的docker里面deepspeed版本不对吗？

**Comment by yiyele** [comment]
deepspeed      0.3.0+f0f2a70
是这个版本吗？我怎么还是有这个问题

**Comment by demomagic** [comment]
我也同样有问题，暂时没找到解决办法

**Comment by demomagic** [comment]
不能用deepspeed 0.3.0+f0f2a70这个版本，我直接更换了最新版本deepspeed==0.3.15

**Comment by demomagic** [comment]
不能用deepspeed 0.3.0+f0f2a70这个版本，我直接更换了最新版本deepspeed==0.3.15，运行正常
