### ISSUE TITLE
使用系统推荐的docker发生RuntimeError: CUDA error: CUBLAS_STATUS_EXECUTION_FAILED问题

### ISSUE THREAD

**Issue by forrestbing** [TsinghuaAI/CPM-1-Finetune#41]
Traceback (most recent call last):
  File "finetune_lm.py", line 315, in <module>
    main()
  File "finetune_lm.py", line 234, in main
    output = model(**batch)
  File "/usr/local/lib/python3.6/dist-packages/torch/nn/modules/module.py", line 547, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/deepspeed/.local/lib/python3.6/site-packages/deepspeed/runtime/engine.py", line 928, in forward
    loss = self.module(*inputs, **kwargs)
  File "/usr/local/lib/python3.6/dist-packages/torch/nn/modules/module.py", line 547, in __call__
    result = self.forward(*input, **kwargs)
  File "/CPM/model/distributed.py", line 78, in forward
    return self.module(*inputs, **kwargs)
  File "/usr/local/lib/python3.6/dist-packages/torch/nn/modules/module.py", line 547, in __call__
    result = self.forward(*input, **kwargs)
  File "/CPM/model/gpt2_modeling.py", line 97, in forward
    transformer_output = self.transformer(embeddings, attention_mask)
  File "/usr/local/lib/python3.6/dist-packages/torch/nn/modules/module.py", line 547, in __call__
    result = self.forward(*input, **kwargs)
  File "/CPM/mpu/transformer.py", line 412, in forward
    hidden_states, attention_mask)
  File "/home/deepspeed/.local/lib/python3.6/site-packages/deepspeed/runtime/activation_checkpointing/checkpointing.py", line 682, in checkpoint
    CheckpointFunction.apply(function, all_outputs, *args)
  File "/home/deepspeed/.local/lib/python3.6/site-packages/deepspeed/runtime/activation_checkpointing/checkpointing.py", line 486, in forward
    outputs = run_function(*inputs_cuda)
  File "/CPM/mpu/transformer.py", line 402, in custom_forward
    x_ = layer(x_, inputs[1])
  File "/usr/local/lib/python3.6/dist-packages/torch/nn/modules/module.py", line 547, in __call__
    result = self.forward(*input, **kwargs)
  File "/CPM/mpu/transformer.py", line 288, in forward
    attention_output = self.attention(layernorm_output, ltor_mask)
  File "/usr/local/lib/python3.6/dist-packages/torch/nn/modules/module.py", line 547, in __call__
    result = self.forward(*input, **kwargs)
  File "/CPM/mpu/transformer.py", line 116, in forward
    mixed_x_layer = self.query_key_value(hidden_states)
  File "/usr/local/lib/python3.6/dist-packages/torch/nn/modules/module.py", line 547, in __call__
^M  0%|          | 0/4128 [00:00<?, ?it/s]    result = self.forward(*input, **kwargs)
  File "/CPM/mpu/layers.py", line 246, in forward

Traceback (most recent call last):
  File "finetune_lm.py", line 315, in <module>
    output_parallel = F.linear(input_parallel, self.weight, self.bias)
  File "/usr/local/lib/python3.6/dist-packages/torch/nn/functional.py", line 1371, in linear
    main()
  File "finetune_lm.py", line 234, in main
    output = model(**batch)
  File "/usr/local/lib/python3.6/dist-packages/torch/nn/modules/module.py", line 547, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/deepspeed/.local/lib/python3.6/site-packages/deepspeed/runtime/engine.py", line 928, in forward
    loss = self.module(*inputs, **kwargs)
  File "/usr/local/lib/python3.6/dist-packages/torch/nn/modules/module.py", line 547, in __call__
    output = input.matmul(weight.t())
RuntimeError: CUDA error: CUBLAS_STATUS_EXECUTION_FAILED when calling `cublasSgemm( handle, opa, opb, m, n, k, &alpha, a, lda, b, ldb, &beta, c, ldc)`
    result = self.forward(*input, **kwargs)
  File "/CPM/model/distributed.py", line 78, in forward
    return self.module(*inputs, **kwargs)
  File "/usr/local/lib/python3.6/dist-packages/torch/nn/modules/module.py", line 547, in __call__
    result = self.forward(*input, **kwargs)
  File "/CPM/model/gpt2_modeling.py", line 97, in forward
    transformer_output = self.transformer(embeddings, attention_mask)
  File "/usr/local/lib/python3.6/dist-packages/torch/nn/modules/module.py", line 547, in __call__
    result = self.forward(*input, **kwargs)
  File "/CPM/mpu/transformer.py", line 412, in forward
    hidden_states, attention_mask)
  File "/home/deepspeed/.local/lib/python3.6/site-packages/deepspeed/runtime/activation_checkpointing/checkpointing.py", line 682, in checkpoint
    CheckpointFunction.apply(function, all_outputs, *args)
  File "/home/deepspeed/.local/lib/python3.6/site-packages/deepspeed/runtime/activation_checkpointing/checkpointing.py", line 486, in forward
    outputs = run_function(*inputs_cuda)
  File "/CPM/mpu/transformer.py", line 402, in custom_forward
    x_ = layer(x_, inputs[1])
  File "/usr/local/lib/python3.6/dist-packages/torch/nn/modules/module.py", line 547, in __call__
    result = self.forward(*input, **kwargs)
  File "/CPM/mpu/transformer.py", line 288, in forward
    attention_output = self.attention(layernorm_output, ltor_mask)
  File "/usr/local/lib/python3.6/dist-packages/torch/nn/modules/module.py", line 547, in __call__
    result = self.forward(*input, **kwargs)
  File "/CPM/mpu/transformer.py", line 116, in forward
    mixed_x_layer = self.query_key_value(hidden_states)
  File "/usr/local/lib/python3.6/dist-packages/torch/nn/modules/module.py", line 547, in __call__
    result = self.forward(*input, **kwargs)
  File "/CPM/mpu/layers.py", line 246, in forward
    output_parallel = F.linear(input_parallel, self.weight, self.bias)
  File "/usr/local/lib/python3.6/dist-packages/torch/nn/functional.py", line 1371, in linear
    output = input.matmul(weight.t())
RuntimeError: CUDA error: CUBLAS_STATUS_EXECUTION_FAILED when calling `cublasSgemm( handle, opa, opb, m, n, k, &alpha, a, lda, b, ldb, &beta, c, ldc)`
Traceback (most recent call last):
  File "/usr/lib/python3.6/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/usr/lib/python3.6/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/usr/local/lib/python3.6/dist-packages/torch/distributed/launch.py", line 246, in <module>
    main()
  File "/usr/local/lib/python3.6/dist-packages/torch/distributed/launch.py", line 242, in main
    cmd=cmd)
subprocess.CalledProcessError: Command '['/usr/bin/python3', '-u', 'finetune_lm.py', '--local_rank=1', '--do_train', '--do_eval', '--data_dir', '/CPM/data/douban/preprocessed/', '--model-parallel-size', '2', '--num-layers', '32', '--hidden-size', '2560', '--load', '/CPM/data/checkpoints/CPM-large', '--num-attention-heads', '32', '--seq-length', '200', '--max-position-embeddings', '1024', '--tokenizer-type', 'GPT2BPETokenizer', '--tokenizer-path', 'bpe_3w_new/', '--vocab-size', '30000', '--lr', '0.00001', '--warmup', '0.1', '--batch-size', '16', '--deepspeed', '--deepspeed_config', '/CPM/scripts/language_model/../ds_config/ds_finetune_lm_large_fp32.json', '--log-interval', '10', '--eval-interval', '100', '--seed', '23333', '--results_dir', 'results/', '--model_name', 'finetune-douban-large-fp32', '--epoch', '1', '--checkpoint-activations', '--deepspeed-activation-checkpointing']' returned non-zero exit status 1.
*****************************************
Setting OMP_NUM_THREADS environment variable for each process to be 1 in default, to avoid your system being overloaded, please further tune the variable for optimal performance in your application as needed.
*****************************************

**Comment by forrestbing** [comment]
请问，有遇到过吗，

**Comment by t1101675** [comment]
可以检查下 CUDA 版本是否匹配
